### ISSUE TITLE
Incorrect dates in the DateSegmentInfo

### ISSUE THREAD

**Issue by SeanLintern** [patchthecode/JTAppleCalendar#1027]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

Preface - I was testing this first in 7.1.6, upgraded today to 7.1.7

1. 7.1.7
2. 7.1.7

So, I have a calendar, input these as a config.

`let start = Date()`
`        let end = Calendar.current.endOfMonth(for: Date().addingTimeInterval(12 * oneMonthTime)) ?? Date()
`
`        return ConfigurationParameters(startDate: start, endDate: end, firstDayOfWeek: .monday)
`

Then when the calendar loads, I check the visible dates to check this month, to get the header title, like in the example project.

When im testing this it was April. So I in the DateSegmentInfo I would expect to see, the remaining days of March in the .inDates, the first days of May in the .outDates and the days of April in the .monthDates. However this is not the case, for the month of April, I get 1 .inDate of "2019-04-28", then in the .monthDates starts with March 28th, then has April up to the 29th, then just starts listing random May dates, then in the outDates, I have the missing 30 April, some May dates and then a date from June?

Attached an image of the visible dates.

![Screenshot 2019-04-03 at 12 53 21](https://user-images.githubusercontent.com/2480548/55476850-86f1c300-560f-11e9-988b-0d094ad18212.png)

After some closer inspection, looking at InternalActionFunctions setupMonthInfoDataForStartAndEndDate() the `startMonth = calendar.startOfMonth(for: validConfig.startDate)` is March 31, but my start date is April 3, and April starts with Monday 1 April, and my firstDayOfWeek is .monday... looks like the function your using for `startOfMonth(for date: Date)` on the Calendar extension is returning 31 March 11:00 pm because its not accounting for daylight savings time?

I have updated the example project with my ConfigurationParameters and the issue is not apparent :(

Here is a look at the visible dates on load, both the example at my project reference the start date as 31/03 when I use 03/04 as my start date.

![Screenshot 2019-04-03 at 14 51 12](https://user-images.githubusercontent.com/2480548/55484243-11422300-5620-11e9-814c-c1cebc3f45d0.png)

As a note, the actual displayed dates are all correct, its just the analysing of the calendar.visibleDates() seems to be incorrect, and I am using the example project code for displaying the month name.

**Comment by patchthecode** [comment]
Can you provide a sample zip file of the error? You can drop the zip file in this chat box.

**Comment by SeanLintern** [comment]
[CalendarTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/3042362/CalendarTest.zip)

Attached a test, i dropped in my exact VC im using, in the exact same manner im using it in my project, and the problem persists

**Comment by patchthecode** [comment]
checking this out now

**Comment by SeanLintern** [comment]
I have imported my files into the example project so i can debug the framework parts. From what I can see, in your calendar the custom override for `layoutAttributesForElements` returns 42 attributes (7*6) but for my calendar it returns 48 values ?

**Comment by patchthecode** [comment]
Found the bug.

In my visible dates, i capture the frame + 1 point. That +1 point started captuing the next month's indates. Fixing this now.

**Comment by patchthecode** [comment]
Fixed on master branch.
Follow the instructions [here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#how-do-i-test-my-project-with-your-latest-code-to-see-if-a-bug-is-fixed-there) to test master branch

**Comment by SeanLintern** [comment]
I dont think it was pushed correctly, there is an error with a var being used called 'extra' that is not initialised? There is also 3 semanticContentAttribute errors?

**Comment by SeanLintern** [comment]
I had to remove the stray 'extra +=1' and change the min deployment to 9.0 on the SDK, but it does seem to get the correct amount of dates now, they are unordered but i think this is due to being horizontal? I manually sort them on willDisplayMonth

**Comment by SeanLintern** [comment]
Unfortunately this doesn't fix the issue, the initial month seems fine, but when i scroll to the next month (May) theres the correct inDates but monthDates has 35 entries? It also gives a different `DateSegmentInfo` depending on if i slightly scroll left/right, if i am on may, scroll left slightly itll report 3 indates, but if i scroll right slightly itll report 2 indates?

**Comment by patchthecode** [comment]
> but when i scroll to the next month (May) theres the correct inDates but monthDates has 35 entries
I see this issue. I didnt filter. Working on this now.

>  It also gives a different DateSegmentInfo depending on if i slightly scroll left/right, if i am on may, scroll left slightly itll report 3 indates, but if i scroll right slightly itll report 2 indates?

Tell me what you calendar scrollMode is set to? is it `.none` ?

**Comment by SeanLintern** [comment]
Default rows (6) and scrollMode is .stopAtEachCalendarFrame

**Comment by SeanLintern** [comment]
With the scroll, I meant, I would scroll left slightly and release, causing the willDisplay to fire, checking the dateSegmentInfo would report 3 inDates, but if i scroll right slightly and release in the same manor, landing on the same month as swiping left, I would get 2 inDates.

**Comment by patchthecode** [comment]
ok let me know when youre online.
Im online now.
--> https://gitter.im/patchthecode/JTAppleCalendar

chat is slow

**Comment by patchthecode** [comment]
Because i just realized there was no bug after all.
I think i broke code and have reverted the fix.
The values you were seeing were correct. 

According to the screen shot you provided, the dates are correct. 
Here is a modified version of your code to print inDates, monthDates, outDates.

[CalendarTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/3055099/CalendarTest.zip)

Now keep scrolling and you will see that the dates are correct.
I used iPhone Xr in portait mode for the test.

**Comment by patchthecode** [comment]
assuming resolved.
closing issue.

I have left the `Awaiting user input flag` set to **ON**

**Comment by patchthecode** [comment]
ok. Are you online now?
Can you go here? 
https://gitter.im/patchthecode/JTAppleCalendar

typing slow here

**Comment by patchthecode** [comment]
I am not saying that there is no bug.
What i am saying is that i did not find a bug using this files you gave me -> [CalendarTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/3042362/CalendarTest.zip)

**Comment by patchthecode** [comment]
finally saw what you are doing.

the error in your code is this
-> 
```
private let inset: CGFloat = 6
calendarView.sectionInset = UIEdgeInsets(top: -inset, left: -inset, bottom: -inset, right: -inset)
```

Why are you doing this?
By making section insets negative you are expanding the sections therefore causing cells to bleed into each other. This is why you are getting the result you posted. It correctly states that there are 48 on screen. If you remove those 2 lines of code everything should work as expected.

**Comment by patchthecode** [comment]
If you are still around, and still need this issue resolved, then open a new one, and reference this link.
I am locking this issue on May/20/2019 because I need a record.
