### ISSUE TITLE
Can't install version 8.0.0 with Carthage

### ISSUE THREAD

**Issue by Dale-One** [patchthecode/JTAppleCalendar#1079]
Hi!

When I try to install the latest version of JTAppleCalendar (8.0.0) with Carthage I get the following error:

`*** Skipped building JTAppleCalendar due to the error:
Dependency "JTAppleCalendar" has no shared framework schemes`

**Comment by patchthecode** [comment]
hmm. Will take a look after work.

**Comment by pcmanik** [comment]
@patchthecode Can you please take a look on that? I would like to update my project. Thanks.

**Comment by patchthecode** [comment]
I am kinda stumped on this one.
Setting the Help wanted flag

**Comment by florianbuerger** [comment]
I looked into this briefly. The project can't be read by Xcode 10, only Xcode 11. When adjusting `objectVersion = 52;` to `objectVersion = 51;` in the `project.pbxproj` file so it can be opened in Xcode 10, there is no framework target for `JTAppleCalendar` at all.

If you have time it would be great if you can recreate the previous project structure. Otherwise I can do it but since I don't know how you want to it it might be best if you do it.

**Comment by sochalewski** [comment]
Bump, could you fix this anytime soon? 🙏

**Comment by patchthecode** [comment]
I'll take a close look at this over the weekend.
In the mean time can you guys just use SwiftPackageManager as a work around?

It comes built into the new XCode 11 making carthage obsolete.

<img width="1106" alt="Screen Shot 2019-07-17 at 11 37 11 am" src="https://user-images.githubusercontent.com/2439146/61389624-3d0fae80-a887-11e9-8def-9378cd9613e5.png">

In Xcode, simply head there, click on the + sign. And paste in this repository's github link

<img width="519" alt="Screen Shot 2019-07-17 at 11 38 17 am" src="https://user-images.githubusercontent.com/2439146/61389717-63354e80-a887-11e9-920e-8276554404b1.png">


Done. 
But yes, i'll take a look over the weekend.

**Comment by patchthecode** [comment]
closing issue.

latest version 8 = 8.0.1 (installed using SPM
latest version 7 = 7.1.8 (installed using carthage/cocoapods)

**Comment by NilaakashSingh** [comment]
Hi, 
Even knowing that this issue is resolved. 
Can we try this workaround 
https://github.com/techprimate/TPPDF/issues/98

**Comment by patchthecode** [comment]
@NilaakashSingh  there was another update to this.

Both Carthage and Cocoapods have been re-enabled for all versions.
If you want to install carthage latest, then please use

```
github "patchthecode/JTAppleCalendar" "master"
```

**Comment by seanrice** [comment]
Hey JT, was having trouble updating to 8.0.0 with Xcode 11.3 ... took your advice and went to SwiftPackageManager ... worked fine, installed 8.0.3 ... and ... I was sure to check remove Carthage based FrameworkSearchPath from my project (!) ... but ... I'm still getting 1 build error ... it's still looking for one vestige of Carthage:

COMPILE ERROR: Failed to read file or folder at ...
/Users/Sean/Developer/Sub4/Carthage/Build/iOS/JTAppleCalendar.framework

I even deleted my derived data folder and cleaned build folders. 

What am I missing?
