### ISSUE TITLE
Wrong selected date

### ISSUE THREAD

**Issue by onurays** [patchthecode/JTAppleCalendar#252]
Version: 6.0

![screen shot 2017-01-02 at 14 04 27](https://cloud.githubusercontent.com/assets/1254401/21588090/d111bcca-d0eb-11e6-96b4-2ed852e628df.png)

Selected Date: (Date) $R0 = **2017-01-09 22:00:00 UTC**

```Swift
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState) {
        handleCellTextColor(view: cell, cellState: cellState)
        handleCellSelection(view: cell, cellState: cellState, date: date, isSelectionEvent: true)
    }
```

Here is my configuration and the problem occurs even if I don't set a timezone.

```Swift
 func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        var calendar = Calendar.current
        calendar.timeZone = TimeZone(secondsFromGMT: NSTimeZone.local.secondsFromGMT())!
        return ConfigurationParameters(startDate: startDate!, endDate: endDate!, numberOfRows: 6, calendar: calendar, generateInDates: .forAllMonths, generateOutDates: .tillEndOfGrid, firstDayOfWeek: .monday)
 }
```

**Comment by patchthecode** [comment]
@onurays this issue was fixed in later version.

can you update to the latest version 6.1.1 ?

**Comment by patchthecode** [comment]
By the way, you are using a lot of defaults.
Your caode can be simplified to this
```swift
 func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        return ConfigurationParameters(startDate: startDate!, endDate: endDate!)
 }
```

**Comment by onurays** [comment]
Thank you for your quick reply. I will be able to test in 12 hours and will post if it is ok or not.

**Comment by patchthecode** [comment]
@onurays sure thing. If the update works, and you find the library useful, a Star Github rating would be greatly loved :)
Have a good one.
Let me know the results.

**Comment by onurays** [comment]
Updated to the 6.1.1 and selected date is still wrong... My timeZone is GMT+2.

**Comment by nlucky** [comment]
Version: 5.0.1 has the same problem ,because we need use swift 2.3 ,so can not update to the latest

**Comment by patchthecode** [comment]
ok.

@onurays  Can I see the following codes?

1. Your current `configureCalendar` function code.
2. The code you are using to print the date on selection

**Comment by patchthecode** [comment]
@nlucky let me resolve this on version 6 first. Then i'll port the fix to you.

**Comment by nlucky** [comment]
@patchthecode thanks

**Comment by dehlen** [comment]
I am also experiencing this issue.

**1. Configure Calendar Code**
`func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let startDate = Date()
        let endDate = Date() + 1.year
        let parameters = ConfigurationParameters(
            startDate: startDate,
            endDate: endDate,
            numberOfRows: 1,
            calendar: Calendar.current,
            generateInDates: .forAllMonths,
            generateOutDates: .tillEndOfGrid,
            firstDayOfWeek: .sunday
        )

        return parameters
    }
`

**2. Code to print the date on selection**
`func calendar(_ calendar: JTAppleCalendarView,
                  didSelectDate date: Date,
                  cell: JTAppleDayCellView?,
                  cellState: CellState) {
        handleCellSelection(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
        self.habitsViewModel.selectedDate.value = date
        print("\(date)")
    }`

**LLDB Output for _po Calendar.current_:**
(lldb) po Calendar.current
▿ gregorian (current)
  - identifier : Foundation.Calendar.Identifier.gregorian
  - kind : "current"
  ▿ locale : Optional<Locale>
    ▿ some : en (current)
      - identifier : "en"
      - kind : "current"
  ▿ timeZone : Europe/Berlin (current)
    - identifier : "Europe/Berlin"
    - kind : "current"
    ▿ abbreviation : Optional<String>
      - some : "GMT+1"
    - secondsFromGMT : 3600
    - isDaylightSavingTime : false
  - firstWeekday : 1
  - minimumDaysInFirstWeek : 1

**Comment by patchthecode** [comment]
@dehlen thanks for the information. I can now replicate your issue. Looking into it now.

**Comment by patchthecode** [comment]
@dehlen I see the issue. I do not believe there is an error. Here are my results. 

I made my time zone information to be the same as yours:
```
▿ gregorian (fixed)
  - identifier : Foundation.Calendar.Identifier.gregorian
  - kind : "fixed"
  ▿ locale : Optional<Locale>
    ▿ some : en (fixed)
      - identifier : "en"
      - kind : "fixed"
  ▿ timeZone : Europe/Berlin (fixed)
    - identifier : "Europe/Berlin"
    - kind : "fixed"
    ▿ abbreviation : Optional<String>
      - some : "GMT+1"
    - secondsFromGMT : 3600
    - isDaylightSavingTime : false
  - firstWeekday : 1
  - minimumDaysInFirstWeek : 1
```

And i had this code:
```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState) {
     handleCellSelection(view: cell, cellState: cellState)
     handleCellTextColor(view: cell, cellState: cellState)
     print(date)
     print(formatter.string(from: date))
}
```

And the results after selecting the `10th` were:
<img width="283" alt="screen shot 2017-01-04 at 9 38 10 am" src="https://cloud.githubusercontent.com/assets/2439146/21652453/8c58f93c-d261-11e6-8ab1-8e54801e8073.png">

```
2017-01-09 23:00:00 +0000 // The result of date
2017 01 10                // The result of formatted date
```

It is important to understand that when you do a `print(date)`  what is happening here is that the print command tries to format that date with its own formatting. This formatting may be different than your timeZone and locale.

In order to print the correct date on console, you need a formatter that is configured with the same `timeZone` and `locale` information of your `Calendar()` instance.

you can do this by:
```
let formatter = DateFormatter()
formatter.timeZone = Calendar.current.timeZone
formatter.locale = Calendar.current.locale
print(formatter.string(from: date))
```

This will give you the same date formatted to your `time zone` rather than what ever default time zone contained in the `print` command.

**Comment by patchthecode** [comment]
@onurays if this also resolves your issue, then feel free to leave a Star Github rating :)
If it does not resolve your issue, then I'll have to do some more digging as to what the problem really is.

**Comment by onurays** [comment]
@patchthecode Unfortunately, I had to switch to the FSCalendar (because of the time pressure). I will try to test it again at weekend.

I know, ```DateFormatter``` formats correctly. But ```po``` or ```print(date)``` doesn't. So we have problems if we need operations on Dates, not Strings.

By the way, you already had your star for this beautiful library :)

**Comment by dehlen** [comment]
Yes you have a point. For me it is important to work with the "local date".
So for me this is resolved likes this: 
- The user clicks on the 04.01.2016
- The date prints 03.01.2016 23:00 which is the correct date in UTC, since i am living in GMT+1
- In order to further work with the date object representing 03.01.2016 23:00 in GMT+1 i am using the following conversion:

```swift
    //date is the object coming from the didSelectDate delegate method
    let dateInRegion = date.inLocalRegion()
    let seconds = dateInRegion.region.timeZone.secondsFromGMT(for: date)
    let localDate = Date(timeInterval: TimeInterval(seconds), since: date)
```

If i now print localDate I get 2017-01-04 00:00:00 +0000 which is the correct date for me as my app proceeds. The above code snippet makes use of the superb SwiftDate library by the way which makes working with dates a lot easier and more convenient. I am not a contributor or anything for the library I just thought I would mention it if people would try to go with my solution and wonder why it does not work for them.

**Comment by patchthecode** [comment]
@dehlen you are exactly correct. I made this library to work with SwiftDate because a number of users requested it. So you can either do the conversion yourself, your you can simply use SwiftDate.

**Comment by onurays** [comment]
@patchthecode All right then, thank you for your afford to reproduce the issue. I also see the same issue with other libraries. So (as an Android developer), this is not a problem for me, anymore. I will format the date and not look at the console :) Thanks again.

**Comment by patchthecode** [comment]
@onurays haha. Yea, when it comes to dates, console can really trip you up if youre not formatting it. Cheers.

**Comment by Cemoo** [comment]
@dehlen hi

I read your answer about the date conversion but i cant see inLocalRegion func for the date from dalegate method. 

Am i wrong or missing something? How to use it that func? did you write it as extension for yourself?

**Comment by patchthecode** [comment]
@Cemoo yes i think he used either a library or some extension.

**Comment by Cemoo** [comment]
Ohh thx for quick answer @patchthecode.

**Comment by Cemoo** [comment]
By the way  i still didnt solve thw issue. Which one is the correct answer ? @patchthecode

**Comment by patchthecode** [comment]
@Cemoo Your selected date is being printed as incorrect?

if this is the case, open a new issue with the exact problem. Also show your `configureCalendar` code and your code that prints the wrong date. I'll answer there.

**Comment by AbdHayek** [comment]
I fixed this problem by modifying the time zone in my device calendar like this :
 `var deviceCalendar = Calendar.current
   deviceCalendar.timeZone = TimeZone(secondsFromGMT: 0)!`

then in JTAppleCalendar ConfigurationParameters returned start date, end date and the previous calendar:
`return ConfigurationParameters(startDate: startDate!, endDate: endDate!, calendar : deviceCalendar)`

**Comment by mudithsilva** [comment]
You can get current Dat by using
`let localDate = Date(timeInterval: TimeInterval(Calendar.current.timeZone.secondsFromGMT()), since: date)`

**Comment by Paccos** [comment]
This may be a dumb/blunt solution but maybe it takes out some of the hassle:

Could those errors be resolved by simply setting the time in the `selectedDate` property to `12:00 UTC` instead of `00:00 UTC` ?

Then the selected day should be the same across the globe and since we're dealing with calendar dates, the timestamp shouldn't be relevant.

Or am I thinking the wrong way?
